### ISSUE TITLE
error 9

### ISSUE THREAD

**Issue by DaxstUz** [GoogleChromeLabs/cronet-sample#10]
throw GooglePlayServices not available due to error 9 . run on android 6.0 device

**Comment by DaxstUz** [comment]
how to set connect timeout?

**Comment by Danstahrg** [comment]
The error originates in Google Play Services and suggests that it's been tampered with ([ref](https://developers.google.com/android/reference/com/google/android/gms/common/ConnectionResult#public-static-final-int-service_invalid)). I covered the topic of request timeouts in https://github.com/GoogleChromeLabs/cronet-sample/issues/11.
