### ISSUE TITLE
How to set request timout?

### ISSUE THREAD

**Issue by wangxin05** [GoogleChromeLabs/cronet-sample#11]
How do I set a request timeout for a request?

**Comment by Danstahrg** [comment]
Cronet doesn't support setting timeouts for requests individually. You can find some details why it's the case in [code comments](https://chromium.googlesource.com/chromium/src/+/lkgr/components/cronet/android/java/src/org/chromium/net/urlconnection/CronetHttpURLConnection.java#453) and [this mail thread](https://groups.google.com/a/chromium.org/g/net-dev/c/z0RxgRNpYh4/m/htlrZAwYKgAJ). 

You can implement your own timeout logic on top of Cronet, cancelling the UrlRequest if it's not completed in a timely fashion.
