### ISSUE TITLE
how to solve this error : ERR_NETWORK_CHANGED?

### ISSUE THREAD

**Issue by harishankar-jayasakthi** [GoogleChromeLabs/cronet-sample#13]
I am getting this error: ERR_NETWORK_CHANGED (cronet post method), is there any solution for this error or increase timeout for API request ??

**Comment by Danstahrg** [comment]
As the error message suggests, this is an error indicating that the transport network changed. You'd need to open new connections as HTTP connections can't be migrated between connections.

In QUIC, you can use connection migration (https://tools.ietf.org/id/draft-tan-quic-connection-migration-00.html, https://source.chromium.org/chromium/chromium/src/+/main:net/quic/quic_context.h;l=126;drc=90f9cdf8e27de8048ef83efe268947871a3f30b7) which handles it for you seamlessly.
