### ISSUE TITLE
The demo is outdated.

### ISSUE THREAD

**Issue by justinzhf** [GoogleChromeLabs/cronet-sample#15]
The demo is outdated. Cause all of the image URLs are not reachable:
            "https://storage.googleapis.com/cronet/sun.jpg",
            "https://storage.googleapis.com/cronet/flower.jpg",
            "https://storage.googleapis.com/cronet/chair.jpg",
            "https://storage.googleapis.com/cronet/white.jpg",
            "https://storage.googleapis.com/cronet/moka.jpg",
            "https://storage.googleapis.com/cronet/walnut.jpg"

**Comment by Danstahrg** [comment]
We have revived the image hosting, the demo is fully functional again.
