### ISSUE TITLE
Why cronet-embedded stopped release new versions.

### ISSUE THREAD

**Issue by ag2s20150909** [GoogleChromeLabs/cronet-sample#20]
The latest official release that can be found is 76.3809.111, which was released on August 20, 2019.
 IETF QUIC draft 29 (h3-29) was added in Chrome/Cronet 85.0.4171.0.
Obviously, it' out of date.Why stop, where to get the latest official binary.
```implementation 'org.chromium.net:cronet-embedded:76.3809.111'```

https://github.com/google/ExoPlayer/issues/9085
https://groups.google.com/a/chromium.org/g/net-dev/c/RdMsMNLwSDw

**Comment by Danstahrg** [comment]
We have restarted our Maven releases. You can now get version 92 from https://maven.google.com/ and we intend to release new versions timely.
